# theme.toml template for a Hugo theme

baseurl = "https://www.santoroland.com/"
title = "santoroland"
theme = "portfolio_lite"
languageCode = "en-us"
timeout = 200000
name = "Portfolio_lite"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "site description here"
homepage = "https://www.santoroland.com"
tags = []
features = []
min_version = "0.88.1"

[author]
  name = "Anthony Luigi Santoro"
  homepage = "https://www.santoroland.com"



