# theme.toml template for a Hugo theme

name = "Portfolio_lite"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://www.santoroland.com"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Anthony Luigi Santoro"
  homepage = "https://www.santoroland.com"


[params]
  author = "Nikola Tesla"
  description = "Tesla's Awesome Hugo Site"

